# Generated by Django 3.1.3 on 2020-11-29 21:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField(default=django.utils.timezone.now)),
                ('how_many_times', models.IntegerField(null=True, default=1)),
                ('comment_from_user', models.TextField(blank=True, default='', max_length=400, null=True)),
                ('link1', models.URLField(blank=True, default='', max_length=400, null=True)),
                ('link2', models.URLField(blank=True, default='', max_length=400, null=True)),
                ('link3', models.URLField(blank=True, default='', max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelWithChangeDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='', max_length=100, null=True)),
                ('description', models.TextField(max_length=400)),
                ('allowed_completition_frequency', models.CharField(max_length=200)),
                ('prize', models.IntegerField(default=0, null=True)),
                ('extra_prize', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('filename_orig', models.CharField(max_length=200, null=True)),
                ('upload_id', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskApproval',
            fields=[
                ('modelwithchangedetection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.modelwithchangedetection')),
                ('is_accepted', models.BooleanField(default=False)),
                ('comment_from_approver', models.TextField(blank=True, default='', max_length=400)),
            ],
            bases=('tasks.modelwithchangedetection',),
        ),
    ]
