# Generated by Django 3.1.3 on 2020-11-29 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentedtask',
            name='file1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='file1', to='tasks.uploadedfile'),
        ),
        migrations.AddField(
            model_name='documentedtask',
            name='file2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='file2', to='tasks.uploadedfile'),
        ),
        migrations.AddField(
            model_name='documentedtask',
            name='file3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='file3', to='tasks.uploadedfile'),
        ),
        migrations.AddField(
            model_name='documentedtask',
            name='task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tasks.task'),
        ),
        migrations.AddField(
            model_name='documentedtask',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskapproval',
            name='approver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskapproval',
            name='documented_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.documentedtask'),
        ),
    ]
