# Generated by Django 3.1.3 on 2020-11-29 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20201129_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentedtask',
            options={'verbose_name': 'udokumentowane zadanie', 'verbose_name_plural': 'udokumentowane zadania'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'zadanie', 'verbose_name_plural': 'zadania'},
        ),
        migrations.AlterModelOptions(
            name='taskapproval',
            options={'verbose_name': 'akceptacja zadań', 'verbose_name_plural': 'akceptacje zadań'},
        ),
        migrations.AddField(
            model_name='documentedtask',
            name='date_last_edited',
            field=models.DateTimeField(default=None, null=True, verbose_name='Data ostatniej edycji'),
        ),
        migrations.AddField(
            model_name='taskapproval',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Zamknięte'),
        ),
        migrations.AlterField(
            model_name='documentedtask',
            name='comment_from_user',
            field=models.TextField(blank=True, default='', max_length=400, null=True, verbose_name='Komentarz użytkownika'),
        ),        
        migrations.AlterField(
            model_name='documentedtask',
            name='how_many_times',
            field=models.IntegerField(default=1, null=True, verbose_name='Ile razy zostało wykonane zadanie'),
        ),
        migrations.AlterField(
            model_name='documentedtask',
            name='date_completed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data ukończenia'),
        ),
        migrations.AlterField(
            model_name='task',
            name='allowed_completition_frequency',
            field=models.CharField(max_length=200, verbose_name='Jak często można wykonywać'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='task',
            name='extra_prize',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Nagroda specjalna'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='task',
            name='prize',
            field=models.IntegerField(default=0, null=True, verbose_name='Nagroda'),
        ),
        migrations.AlterField(
            model_name='taskapproval',
            name='comment_from_approver',
            field=models.TextField(blank=True, default='', max_length=400, verbose_name='Komentarz od akceptującego'),
        ),
        migrations.AlterField(
            model_name='taskapproval',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Zaakceptowane'),
        ),
        migrations.CreateModel(
            name='FavouriteTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tasks.task')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ulubione zadanie',
                'verbose_name_plural': 'ulubione zadania',
            },
        ),
    ]
