# Generated by Django 3.1.3 on 2020-11-29 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accrued', models.DateTimeField(default=django.utils.timezone.now)),
                ('accrual', models.IntegerField(default=0, null=True)),
                ('accrual_extra_prize', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('accrual_deleted', models.BooleanField(default=False)),
                ('accrual_type', models.CharField(max_length=10)),
                ('year_week', models.CharField(max_length=8)),
            ],
        ),
    ]
