# Generated by Django 3.1.3 on 2020-12-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
