# Generated by Django 3.1.3 on 2020-12-02 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_image', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Link do obrazu')),
                ('name_eng', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Nazwa angielska')),
                ('name_pl', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Nazwa polska')),
                ('description', models.TextField(help_text='Można używać tagów HTML', max_length=1000, verbose_name='Opis')),
                ('category', models.CharField(blank=True, choices=[('minecraft_item', 'Przedmioty z Minecrafta'), ('building', 'Budynki'), ('other', 'Inne')], default='other', max_length=100, null=True, verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'przedmiot',
                'verbose_name_plural': 'przedmioty',
            },
        ),
        migrations.CreateModel(
            name='ItemOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, null=True, verbose_name='Cena')),
                ('is_available', models.BooleanField(default=True, null=True, verbose_name='Czy dostępny')),
                ('item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.item')),
            ],
            options={
                'verbose_name': 'oferta przedmiotu',
                'verbose_name_plural': 'oferty przedmiotów',
            },
        ),
    ]
