# Generated by Django 3.1.3 on 2020-12-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_request_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nazwa'),
        ),
    ]
