# Generated by Django 3.1.3 on 2020-12-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_request_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nazwa'),
        ),
    ]
