# Generated by Django 3.1.3 on 2020-12-02 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_itemoffer'),
        ('shop', '0004_auto_20201202_2117'),
    ]

    operations = [
    ]
