# Generated by Django 3.1.3 on 2020-12-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_merge_20201203_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='content',
            field=models.TextField(help_text='Można używać tagów HTML', verbose_name='Opis prośby'),
        ),
        migrations.AlterField(
            model_name='request',
            name='link1',
            field=models.URLField(blank=True, default='', max_length=400, null=True, verbose_name='Link 1'),
        ),
        migrations.AlterField(
            model_name='request',
            name='link2',
            field=models.URLField(blank=True, default='', max_length=400, null=True, verbose_name='Link 2'),
        ),
        migrations.AlterField(
            model_name='request',
            name='link3',
            field=models.URLField(blank=True, default='', max_length=400, null=True, verbose_name='Link 3'),
        ),
    ]
