# Generated by Django 3.1.3 on 2020-11-29 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Można używać tagów HTML')),
                ('hint', models.CharField(max_length=400)),
                ('answer', models.CharField(max_length=400)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Kiedy ma być opublikowany')),
            ],
        ),
    ]
