# Generated by Django 3.1.3 on 2020-11-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scout',
            name='rank',
            field=models.CharField(choices=[('', 'bez stopnia'), ('mł.', 'mł.'), ('wyw.', 'wyw.'), ('ćwik', 'ćwik'), ('HO', 'HO'), ('pwd. HO', 'pwd. HO'), ('HR', 'HR'), ('pwd. HR', 'pwd. HR'), ('phm. HR', 'phm. HR'), ('hm. HR', 'hm. HR')], default='bezstopnia', max_length=20),
        ),
    ]
