# Generated by Django 3.1.3 on 2020-11-29 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('date_time', models.DateTimeField(blank=True, verbose_name='Data utworzenia')),
                ('pub_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kiedy ma być opublikowany')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('content', models.TextField(help_text='Można używać tagów HTML', verbose_name='Treść')),
                ('link1', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Link 1')),
                ('link2', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Link 2')),
                ('link3', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Link 3')),
            ],
        ),
    ]
